version: '3.5'
services:
  axonserver:
    image: 'axoniq/axonserver'
    hostname: 'axon-server'
    ports:
      - '8024:8024'
      - '8124:8124'
      - '8224:8224'
  mongodb:
    image: 'mongo:latest'
    hostname: 'mongo-server'
    ports:
      - '27017:27017'
  mysql:
    image: mysql:5.7.38
    hostname: mysql-server
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin
      - MYSQL_DATABASE=basic_db
