server:
  port: 8081

spring:
  data:
    mongodb:
      host: ${DOCKER_IP:192.168.59.100}
      port: 27017
      database: user

axon:
  axonserver:
    servers: ${DOCKER_IP:192.168.59.100}

initial:
  user:
    id: 0
    firstName: John
    lastName: Doe
    email: john.doe@example.com
    account:
      username: admin
      password: admin
      roles:
        - READ_PRIVILEGE
        - WRITE_PRIVILEGE

